### PR TITLE
Add re-process action

### LINKED ISSUE #161: Add `Re-Process` action
Organization admin can choose to re-process a pin by sending it back to an assinged department to process it again. State will be change from `RESOLVED` back to `PROCESSING`.

### PR DESCRIPTION
**Pull request by supasate**
Fix #161 

Merge #175 first

### CODE REVIEW

**Comment by parnurzeal** [comment]
Not sure I understand. Why can't we just use PROCESS?

**Comment by supasate** [comment]
PROCESS is used for the case that `department_head` accepts a pin to process.
RE-PROCESS is used for the case that `organization_admin` send pin back to re-process.

Different behavior and results in different activity log.

**Comment by parnurzeal** [comment]
Still feeling that this is redundant. Ex. if we use PROCESS, we can
identify easily whether it is artificially REPROCESS by querying for the
action to change PROCESS by organization_admin.

On Dec 21, 2016 12:23 AM, "Supasate Choochaisri" <notifications@github.com>
wrote:

PROCESS is used for the case that department_head accepts a pin to process.
RE-PROCESS is used for the case that organization_admin send pin back to
re-process.

Different behavior and results in different activity log.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/youpin-city/youpin-api/pull/176#issuecomment-268287355>,
or mute the thread

**Comment by parnurzeal** [comment]
I think I understand now. Kinda confused between actions and states... 
Merging.

**Pull request merged**
