### PR TITLE
Run eslint after test

### PR DESCRIPTION
**Pull request by supasate**

### CODE REVIEW

**Comment by parnurzeal** [comment]
Failed. Please check.

**Comment by supasate** [comment]
Yes, it failed because I added linter to check. I wait other PRs to be merge first before fixing coding style.

**Comment by supasate** [comment]
I'm going to fix them all in this PR.

**Comment by supasate** [comment]
@parnurzeal Brute force! Done!

**Comment by parnurzeal** [comment]
Too good to be true~ :P 

So nice!

**Pull request merged**
