### PR TITLE
Send notif when user updates a pin with PROCESSING state

### PR DESCRIPTION
**Pull request by parnurzeal**

### CODE REVIEW

**Comment by parnurzeal** [comment]
Please hold on. Test results are weird because of the previous PR.
https://travis-ci.org/youpin-city/youpin-api/jobs/211179091

**Comment by parnurzeal** [comment]
I found two error mesages:

1.)  ✓ return 201 when posting by authenticated user, using correct owner id, and filling all required fields (142ms)
(node:9505) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: TypeError: Cannot read property 'description' of undefined

2.) ✓ updates correct properties for `assigned` transtion (131ms)
(node:9505) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Error: getaddrinfo ENOTFOUND your your:80

These do not happen on my local machine. 
https://travis-ci.org/youpin-city/youpin-api/jobs/212658153

Still cannot find the culprit of this error on TravisCI.

**Comment by supasate** [comment]
The symptom is similar to when organization_admin logs in without department. Is it related?

**Comment by parnurzeal** [comment]
@supasate Can you point me to the PR that held the similar symptom? I am not sure how it is similar.

**Comment by supasate** [comment]
This one youpin-city/youpin-web-admin#120.

**Comment by parnurzeal** [comment]
Hmm.. I dun see how it is similar. Maybe it is not related.

**Pull request closed without merging**
