### PR TITLE
Reorganise auth-non-related hooks into utils folder

### PR DESCRIPTION
**Pull request by parnurzeal**
Make hooks universally in the same format + add some more test accordingly.

Next PR will move API KEY authentication hooks into utils folder.

### CODE REVIEW

**Comment by supasate** [comment]
Why do we need to move hooks out of the hook folder to `utils` folder?

IMO, `swapLatLongHelper` can be moved into `utils` because it's not a hook and everyone can use it (it can also be renamed to just `swapLatLong` when moved).

However, `swapLatLong`, `restrictToOwnerOfPin`, and `validateObjectId` hooks are ....um.... hooks. So, they are served as hooks not utility functions. 

So, I'm not sure why we need to move them outside the hook folder.

In case we need it, another option is moving them to `/utils/hooks/` to explicitly state that they will be used as hooks only.

What do you think?

**Comment by parnurzeal** [comment]
I was thinking the same in the first place... 
But I saw you created a new validateObjectId in utils folder even though we are using it as a hook.
People will get confused whether they should put these functions in hooks or in utils. 

That's why I decided to move everything to utils as same as validateObjectId one...

**Comment by parnurzeal** [comment]
Anyway, let's do this.

I think I like `utils/hooks`. 
Let move all hooks (`authenticateAPI`, `restrictToOwnerOfPin`,  `swapLatLong`, and `validateObjectId`) to under `utils/hooks`

**Comment by supasate** [comment]
Oh that's my bad. So, move to 'utils/hooks' then.

**Comment by parnurzeal** [comment]
PTAL.

**Comment by supasate** [comment]
LGTM

**Pull request merged**
